#!/bin/bash

# Build environment must be passed
cd ${BUILD_DIR} || exit $?

# Ensure our group and user exists by name and number.  Bitbake
# refuses to run as root and various packages and rules will fail if
# the userid is not defined.
groupadd -f -g ${BUILD_GID} ${BUILD_GROUP} || exit $?
useradd -u ${BUILD_UID} -g ${BUILD_GROUP} ${BUILD_USER} || exit $?

# Run the build as the user and group invoking us
setuser ${BUILD_USER} bash -c ". ./env-oe.sh ; bitbake ${*}"

echo $?
