#!/bin/bash

progname=$(basename $0)

# Build environment must be passed
test -n "${BUILD_DIR}" || exit $?
cd ${BUILD_DIR} || exit $?

# Ensure our group and user exists by name and number.  Bitbake
# refuses to run as root and various packages and rules will fail if
# the userid is not defined.
groupadd -f -g ${BUILD_GID} ${BUILD_GROUP} || exit $?
useradd -u ${BUILD_UID} -g ${BUILD_GROUP} ${BUILD_USER} || exit $?

# Figure out what we are supposed to do
case ${progname} in
    bitbake)
	setuser ${BUILD_USER} bash -c ". ./env-oe.sh ; bitbake ${*}"
	;;
    setup*)
	setuser ${BUILD_USER} bash -c ". ./setup.sh ${*}"
	;;
    *)
	echo "Unknown script link ${progname}" 2>&1
	exit 1
	;;
esac

echo $?
