#!/bin/sh

# Change value returned by uname -r for broken programs that examine it

UNAME=/bin/uname
VERSION=$(${UNAME} -r)
OLD_VERSION=3.13.0-98-generic

output=$(${UNAME} ${*})
rc=$?

echo "${output}" | sed -e "s/${VERSION}/${OLD_VERSION}/"
exit ${rc}
