#!/bin/bash -x

set -x

# Build environment must be passed
test -n "${BUILD_DIR}" || exit $?
cd ${BUILD_DIR} || exit $?

# Ensure our group and user exists by name and number.  Bitbake
# refuses to run as root and various packages and rules will fail if
# the userid is not defined.
groupadd -f -g ${BUILD_GID} ${BUILD_GROUP} || exit $?
useradd -u ${BUILD_UID} -g ${BUILD_GROUP} ${BUILD_USER} || exit $?

# Figure out what we are supposed to do
if [ "${1}" == "--setup" ]; then
    shift
    setuser ${BUILD_USER} bash -c ". ./setup.sh ${*}"
    exit $?
fi

rc=-1
for script in ./env-oe.sh ./oe-init-build-env; do
    test -f ${script} || continue
    setuser ${BUILD_USER} bash -c ". ${script}; bitbake ${*}"
    rc=$?
    break
done

if [ ${rc} -eq -1 ]; then
    echo "Unable to find environment init script" >&2
    rc=1
fi

exit  $?
