#!/bin/bash -x

# Build environment must be passed
test -n "${BUILD_DIR}" || exit $?
cd ${BUILD_DIR} || exit $?

# Ensure our group and user exists by name and number.  Bitbake
# refuses to run as root and various packages and rules will fail if
# the userid is not defined.
groupadd -f -g ${BUILD_GID} ${BUILD_GROUP} || exit $?
useradd -u ${BUILD_UID} -g ${BUILD_GROUP} ${BUILD_USER} || exit $?

# Figure out what we are supposed to do
if [ "${1}" == "--setup" ]; then
    setuser ${BUILD_USER} bash -c ". ./setup.sh ${*}"
    exit $?
fi

# Find and run our envivronment setup script
for script in ./env-oe.sh ./oe-init-build-env; do
    if [ test -f ${script} ]; then
	break
    fi
done
if [ -z "${script}" ]; then
    echo "Environment setup script not found" >&2
    exit 1
fi

setuser ${BUILD_USER} bash -c ". ${script}; bitbake ${*}"
exit $?
